sudo: false

language: node_js

node_js:
  - "8"

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm i -g @angular/cli@next
  - npm i -g cordova

script:
  - cd template_src
  - npm install
  - npm run build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
